---

- name: Verify required variables are defined
  ansible.builtin.assert:
    that:
      - grafana_admin_user is defined
      - grafana_admin_pass is defined
      - grafana_secret_key is defined
      - grafana_domain_name is defined
    fail_msg: "Required variable is not defined. See role documentation for required variables."

- name: Include install tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

# If grafana_user is defined, we assume non-standard dir paths
- name: Create Grafana data and log directories
  when: grafana_user is defined
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_user }}"
    group: "{{ grafana_user }}"
    mode: "0750"
  loop:
    - "{{ grafana_data_dir }}"
    - "{{ grafana_log_dir }}"

- name: Create Grafana config directory
  when: grafana_user is defined
  ansible.builtin.file:
    path: "{{ grafana_conf_dir }}"
    state: directory
    mode: "0750"

- name: Copy Grafana configs
  ansible.builtin.template:
    src: "grafana.ini.j2"
    dest: "{{ grafana_conf_dir }}/grafana.ini"
    group: "{{ grafana_group | default(omit) }}"
    mode: "0640"
    backup: "{{ grafana_backup_configs }}"
  notify:
    - Restart grafana

# Force a restart in case connection params have changed
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Grafana is started and running
  ansible.builtin.systemd_service:
    name: "{{ grafana_service_name }}"
    state: started
    enabled: true

- name: Install Grafana plugins
  community.grafana.grafana_plugin:
    name: "{{ item }}"
  loop: "{{ grafana_plugins | default([]) }}"
